// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
//import "dotenv/config";
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";
dotenv.config({ path: "../../.env" }); //is being ignore because its in dbMain.ts
//import { env } from "node:process";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"] as string,
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"] as string, 
  },
});
