#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" <<EOF
CREATE USER "$PRISMA_USER" WITH PASSWORD '$PRISMA_PASSWORD';

CREATE DATABASE "$POSTGRES_DB_MAIN" OWNER "$PRISMA_USER";
CREATE DATABASE "$POSTGRES_DB_SHADOW" OWNER "$PRISMA_USER";

CREATE USER "$ADMIN_USER" WITH PASSWORD '$ADMIN_PASSWORD' SUPERUSER;
EOF