server {
    listen 80;
    server_name green-hawk-50680.zap.cloud;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    return 301 https://$host$request_uri;
}



server {

    listen 443 ssl;
    server_name green-hawk-50680.zap.cloud;
	
	location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
	
	ssl_certificate /etc/letsencrypt/live/green-hawk-50680.zap.cloud/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/green-hawk-50680.zap.cloud/privkey.pem;


    # Angular
    location / {
        root /usr/share/nginx/html;
		try_files $uri $uri/ /index.html;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        # Angular dev server
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }


	location /api/swagger/ {
		proxy_pass http://api:3000;
		proxy_http_version 1.1;

		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
	}

    # Node API
    location /api/ {

        proxy_pass http://api:3000;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }


    # Adminer
    location /adminer.php {

        proxy_pass http://adminer:8080;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}