// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
//import "dotenv/config";
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";
//dotenv.config({ path: "../../../.env" }); //is being ignored because its in dbMain.ts
//import { env } from "node:process";

export default defineConfig({
  schema: "src/db/prisma/schema.prisma",
  migrations: {
    path: "src/db/prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL!,
    shadowDatabaseUrl: process.env.SHADOW_DATABASE_URL!, 
  },
});
